### ISSUE TITLE
ImportError: failed to find libmagic

### ISSUE THREAD

**Issue by Limych** [Limych/media_player.linkplay#13]
2019-12-29 19:28:53 ERROR (MainThread) [homeassistant.helpers.entity] Update for media_player.kitchen fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 281, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 461, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/linkplay/media_player.py", line 764, in update
    self._update_from_id3()
  File "/config/custom_components/linkplay/media_player.py", line 656, in _update_from_id3
    import eyed3
  File "/usr/local/lib/python3.7/site-packages/eyed3/__init__.py", line 32, in 
    from .utils.log import log                                          # noqa: E402
  File "/usr/local/lib/python3.7/site-packages/eyed3/utils/__init__.py", line 27, in 
    import magic
  File "/usr/local/lib/python3.7/site-packages/magic.py", line 181, in 
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation

**Comment by smgt** [comment]
The fix to this problem is as the error message say, install libmagic. eye3d uses it to parse id3 tags I guess.

**Comment by Munken** [comment]
Why not do as suggested?

https://community.home-assistant.io/t/linkplay-integration/33878/120?u=munken
