### ISSUE TITLE
Update for media_player.audiopro fails

### ISSUE THREAD

**Issue by favarinbarracano** [Limych/media_player.linkplay#5]
## Version of the custom_component
1.1.2 commit: 2db347b

## Configuration
media_player:
  - platform: linkplay
    host: 192.XXX.XXX.XXX
    devicename: AudioPro_C3_XXXXXX
    name: 'AudioPro C3'

## Describe the bug
Update for media_player.audiopro_c3 fails

## Debug log
Log Details (ERROR)
Fri Aug 23 2019 13:19:17 GMT+0200 (CEST)

Update for media_player.audiopro_c3 fails
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity.py", line 249, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/app/homeassistant/helpers/entity.py", line 419, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/linkplay/media_player.py", line 701, in update
    if upnpclient.Device(entry.location).friendly_name == \
  File "/usr/local/lib/python3.7/site-packages/upnpclient/upnp.py", line 131, in __init__
    self._read_services()
  File "/usr/local/lib/python3.7/site-packages/upnpclient/upnp.py", line 180, in _read_services
    findtext('eventSubURL')
  File "/usr/local/lib/python3.7/site-packages/upnpclient/upnp.py", line 235, in __init__
    self.scpd_xml = etree.fromstring(resp.content)
  File "src/lxml/etree.pyx", line 3234, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1876, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1764, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1127, in lxml.etree._BaseParser._parseDoc
  File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 640, in lxml.etree._raiseParseError
  File "<string>", line 1
lxml.etree.XMLSyntaxError: Document is empty, line 1, column 1

**Comment by svemat01** [comment]
#12
